name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.6"
          - "9.4.4"
        platform:
        - "macos-latest"
        - "ubuntu-latest"
        - "windows-latest"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}
      
      - name: Compile
        run: cabal build