name: "stack"

on:
  push:
    branches:
      - main
      - action-test

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  stack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resolver: [lts-18, lts-19, nightly]
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          enable-stack: true
      
      - name: Compile
        run: stack build --resolver=${{ matrix.resolver }}